[package]
name = "simple_game"
version = "0.1.0"
authors = ["Mineau Jean-Marie <mineau.jean.marie@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.sdl2]
version = "0.32.1"
default-features = false
features = ["image"]
